server:
  port: 8081
  servlet:
    context-path: /products

limit:
  minPrice: 0.01
  maxPrice: 999999
  description: at least ${limit.minPrice}dollars, max is ${limit.maxPrice}dollars

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/joole_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: sher
    password: woods89
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect